common_with_devs_repos: true
common_hpckit_derivatives:
- main
- slurm24.05
slurm_with_jwt: false
slurm_params:
  PriorityType: priority/multifactor
  PriorityWeightFairshare: 1000
  PriorityWeightQOS: 100
  SelectType: select/cons_tres
slurm_partitions:
- name: batch
  nodes: cn[001-080,101-980]
  default: yes
  params:
    MaxTime: INFINITE
    State: UP
    DefMemPerCPU: 512
- name: debug
  nodes: cn[081-099]
  params:
    MaxTime: "1:0:0"
    State: UP
    DefMemPerCPU: 512
- name: interactive
  nodes: cn100
  params:
    MaxTime: "10:00"
    State: UP
    DefMemPerCPU: 512
- name: ia
  nodes: gn[01-40]
  params:
    MaxTime: "10:00"
    State: UP
    DefMemPerCPU: 512
slurm_qos:
- name: critical
  args:
  - GrpJobs=300
  - MaxWall=2-00:00:00
  - MaxJobsPU=10
  - MaxSubmitJobsPU=20
  - MaxSubmitJobsPA=30
  - Priority=200
slurmweb_enabled: true
slurmweb_agent_settings:
  metrics:
    enabled: true
redis_enabled: true
metrics_enabled: true
