common_with_devs_repos: true
slurm_with_jwt: false
slurm_params:
  PriorityType: priority/multifactor
  SelectType: select/cons_res
slurm_qos:
- name: study
  args:
  - Flags=OverPartQOS
  - GrpTRES=node=50
  - GrpJobs=60
  - MaxTRES=cpu=48
  - MaxWall=8:00:00
  - MaxTRESPU=cpu=10,mem=5
  - MaxTRESPA=cpu=15,mem=10
  - MaxJobsPU=10
  - MaxSubmitJobsPU=20
  - MaxSubmitJobsPA=30
  - Priority=100
slurmweb_enabled: true
redis_enabled: true
